class StorageError(Exception):
    """Вызвается в случае ошибки доступа к данным в хранилище."""
